testing triggering errors

diff --git a/.github/workflows/react-lint.yml b/.github/workflows/react-lint.yml
--- a/.github/workflows/react-lint.yml
+++ b/.github/workflows/react-lint.yml
@@ -35,4 +35,11 @@ jobs:
         docker compose -f BuildTools/docker-compose.yml up -d --build --remove-orphans frontend
     - name: EsLint
       run: |
-        docker exec stocks_frontend /bin/bash -c 'cd src; npx eslint $(find ./ -name "*.js" | grep -vP ".test.js")'
+        docker exec stocks_frontend /bin/bash -c 'cd src; npx eslint $(find ./ -name "*.js" | grep -vP ".test.js")' > eslint.results.log
+        if grep -qP '[0-9]+ problems' eslint-results.txt; then
+          echo "ESLint found errors."
+          exit 1
+        else
+          echo "ESLint passed."
+        fi
+        
